-- CREATE TABLE client (
--   aggregate_id     VARCHAR(255) NOT NULL,
--   aggregate_status INTEGER,
--   version          BIGINT,
--   name             VARCHAR(255),
--   PRIMARY KEY (aggregate_id)
-- );
CREATE TABLE customer (
  aggregate_id     VARCHAR(255) NOT NULL,
  aggregate_status INTEGER,
  version          BIGINT,
  activity         VARCHAR
                   (255),
  city             VARCHAR(255),
  post_code        VARCHAR(255),
  street           VARCHAR(255),
  name             VARCHAR(255),
  PRIMARY KEY (aggregate_id)
);
--
-- CREATE TABLE order (
--   aggregate_id      VARCHAR(255) NOT NULL,
--   aggregate_status  INTEGER,
--   version           BIGINT,
--   creation_date     TIMESTAMP,
--   creator           VARCHAR(20)  NOT NULL,
--   modification_date TIMESTAMP,
--   modifier          VARCHAR(20)  NOT NULL,
--   client_id         VARCHAR(255) NOT NULL,
--   status            VARCHAR(255),
--   PRIMARY KEY (aggregate_id)
-- );
--
-- CREATE TABLE order_item (
--   entity_id            BIGINT,
--   quantity             INTEGER NOT NULL,
--   product_aggregate_id VARCHAR(255), ORDER VARCHAR (255),
--   PRIMARY KEY (entity_id)
-- );
--
-- CREATE TABLE product (
--   aggregate_id     VARCHAR(255) NOT NULL,
--   aggregate_status INTEGER,
--   version          BIGINT,
--   name             VARCHAR(255),
--   money            DECIMAL(19, 2),
--   product_type     VARCHAR(255),
--   PRIMARY KEY (aggregate_id)
-- );
--
CREATE TABLE sequence (
  id bigint generated by default as identity,
  name      VARCHAR(255) NOT NULL,
  separator VARCHAR(255),
  sequence  INTEGER      NOT NULL,
  PRIMARY KEY (id)
);
--
alter table sequence add constraint UKfjqyxmtlmj9s4oro29y6u43w6 unique (name)
-- alter table order_item add constraint FKlo7ulnkmrb2j4kcttid9xrr6o foreign key (product_aggregate_id) references product;
-- alter table order_item add constraint FKsrnghl54y476h7bidk7wkpgfo foreign key (order) references order;